apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: YOUR_IMAGE_URI_HERE # <-- IMPORTANT: Replace with your actual image URI from ECR or other registry
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m" # Request 0.1 CPU core
            memory: "128Mi" # Request 128 MiB of memory
          limits:
            cpu: "500m" # Limit to 0.5 CPU core
            memory: "256Mi" # Limit to 256 MiB of memory
        env:
          - name: DB_HOST
            value: "<rds_endpoint_from_terraform_output>" # TODO: Replace with actual RDS endpoint or use a ConfigMap/Secret
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config # Assuming a ConfigMap named app-config exists
                key: db_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials # Assumes a secret named db-credentials exists
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials # Assumes a secret named db-credentials exists
                key: password
          # TODO: Add environment variables for S3 bucket name if needed
          # - name: S3_BUCKET_NAME
          #   value: "<s3_bucket_name_from_terraform_output>"
      # TODO: Add RBAC configuration (ServiceAccount) if needed for AWS permissions (IRSA)
      # serviceAccountName: your-service-account 